### ISSUE TITLE
Sponsorship / donation?

### ISSUE THREAD

**Issue by Jaxkr** [cetra3/tmq#26]
This project seems to be the only proper working implementation of ZeroMQ for Tokio. I want to make sure it stays healthy and I'd love to kick the maintainers a couple of bucks a month.

Does it currently have corporate backing? Did someone make this at work where it is currently used in production? If so, I feel confident using this library.

If it's a hobby project, I'd love to donate.

**Comment by cetra3** [comment]
Hi @Jaxkr that's very generous of you.  It was built for a product I used in an older company that I'm no longer working for, but will probably see use again in some form, which is why I'm interested in maintaining it.

However, I don't feel that I should personally be compensated for it since it was built for profit!  Other maintainers may have differing opinions here and I'll invite them to weigh in

**Comment by skrap** [comment]
Hi! I certainly have only done a small portion of the work on this crate, but I am doing it with the backing of my (small) employer.  We only use a narrow subset of the ZMQ API, so I think my contributions will probably be limited to maintaining those aspects of the tmq API which already exist, rather than any expansion at this point.
